### ISSUE TITLE
Tambah link linkedin di tentang jendela. :p #narsis

### ISSUE THREAD

**Issue by yoelsumitro** [jendela/jendela#115]
Ixon: https://uk.linkedin.com/in/ikhsanassaat
Alsa: https://id.linkedin.com/in/alsasian
Cyndy; https://sg.linkedin.com/in/cyndymessah
Yoel: https://de.linkedin.com/in/yoelsumitro

**Comment by ikhsan** [comment]
demi karir yang makin cemerlang

**Comment by yoelsumitro** [comment]
Belon di push yah son?

**Comment by ikhsan** [comment]
Have pushed to dev. Not yet to prod because I'm bundling it with new footer.
