### ISSUE TITLE
Weird map layouting

### ISSUE THREAD

**Issue by alsasian** [jendela/jendela#36]
![2015-12-02 13-16-58](https://cloud.githubusercontent.com/assets/312472/11530694/119980b2-98f7-11e5-883b-88224ddfa0cf.png)

Environment: 
- OS: Windows 7
- Browser: Opera 33.0.1990.115

**Comment by alsasian** [comment]
![img-20151202-wa0003](https://cloud.githubusercontent.com/assets/312472/11530819/251c29d6-98f8-11e5-9a5f-9f171c132493.jpg)

Environment:
- Device: iPad
- OS: iOS
- Browser: Safari

**Comment by ikhsan** [comment]
Sa, which version of Opera did you use?

**Comment by alsasian** [comment]
Inpoh updated son

**Comment by ikhsan** [comment]
I'll put this to low priority for now since.. who is using opera nowadays :stuck_out_tongue:

**Comment by ikhsan** [comment]
upgrading it back to bug because the map doesn't look good on big screens
