### ISSUE TITLE
page layouting

### ISSUE THREAD

**Issue by ikhsan** [jendela/jendela#39]
- [x] add review
- [x] review
- [x] public services
- [x] faq / about

**Comment by ikhsan** [comment]
faq is done by #47

**Comment by yoelsumitro** [comment]
Ini nurut gw paling penting!

**Comment by ikhsan** [comment]
services :point_right: #54

**Comment by ikhsan** [comment]
#57 :point_left: add review page

**Comment by ikhsan** [comment]
review page is done!
:point_down: 
#70

**Comment by ikhsan** [comment]
closing this, and move the statistic layout bit to #19
