### ISSUE TITLE
Mobile app with react native

### ISSUE THREAD

**Issue by ikhsan** [jendela/jendela#4]

**Comment by rrmdn** [comment]
i can help in react native if you need some

**Comment by ikhsan** [comment]
hi @rromadhoni, thank you for your interest! We gladly accept any help from more contributors.

Although, we might need to prepare our repo first before moving forward. Might need to refactor our code so that we can use the same core for our site and mobile apps. We will let you know!

**Comment by rrmdn** [comment]
Of course, i forgot about parse sharing code :D let me know when we are able get started
