### ISSUE TITLE
Label untuk lihat review "urutkan berdasarkan"

### ISSUE THREAD

**Issue by yoelsumitro** [jendela/jendela#61]

**Comment by alsasian** [comment]
@yoelsumitro formnya udah terlalu mepet untuk ditambahin label, jadi gw ganti isi combo boxnya jadi [ulasan terakhir, biaya termahal, ulasan terbaik]. make sense ga?

**Comment by yoelsumitro** [comment]
tambahin at least "sort by" gimana. Gw tau aneh pake inggris tapi itu plg singkat dan mending biar lebih jelas

**Comment by alsasian** [comment]
Fixed in https://github.com/jendela/jendela/pull/100
