### ISSUE TITLE
layout informasi lainnya, diganti jadi 4 per line kalau lebih bagus, laiinnya dihapus

### ISSUE THREAD

**Issue by yoelsumitro** [jendela/jendela#63]

**Comment by alsasian** [comment]
![image](https://cloud.githubusercontent.com/assets/312472/11610289/3fd17c92-9b9e-11e5-8827-7e1b5d2f612c.png)
4 per line

**Comment by ikhsan** [comment]
looks good to me :+1:

**Comment by alsasian** [comment]
![image](https://cloud.githubusercontent.com/assets/312472/11610293/5bd8e952-9b9e-11e5-8b88-a7720c45d843.png)
6 per line

**Comment by ikhsan** [comment]
mksdnya ke yang 4 per line

**Comment by alsasian** [comment]
6 per line seems ideal for the desktop view. small device on 2 per line, and medium on 4 per line.

**Comment by ikhsan** [comment]
I'll close this for now since we have reached an agreement
