### ISSUE TITLE
Add "situs resmi" for each public service

### ISSUE THREAD

**Issue by alsasian** [jendela/jendela#69]

**Comment by yoelsumitro** [comment]
Gw lebih prefer ga dimasukin sih sa buat tahap skrg. Walaupun aga cheaty krn gw pgn ngasih kesan kalau kita gather infonya ga dari web lain tp dari instasi terkait

SIM : http://satulayanan.id/
STNK http://satulayanan.id/
e-KTP http://satulayanan.id/
Kartu Keluarga http://www.jakarta.go.id/
Akta Nikah http://www.jakarta.go.id/
Akta Kawin http://www.jakarta.go.id/
Akta Cerai http://www.jakarta.go.id/
