### ISSUE TITLE
Wiring up Reviews

### ISSUE THREAD

**Issue by ikhsan** [jendela/jendela#71]
##### Lihat ulasan
- [x] panel always shows province info
- [x] unselected province means showing Indonesia's info
- [x] 'tulis ulasan' link should bring province/kota as the parameters, and select them by default

**Comment by alsasian** [comment]
on going https://github.com/jendela/jendela/tree/fix-reviewwiring

**Comment by alsasian** [comment]
fixed in https://github.com/jendela/jendela/pull/73
