### ISSUE TITLE
Field rating di tulis ulasan

### ISSUE THREAD

**Issue by yoelsumitro** [jendela/jendela#90]
sekarang bentuknya dropdown, better pake kaya click bintang biar tahu kalau 1 itu sangat jelek, 5 sangat baik.

untuk sementara kalau solusi ini susah diimplementasiini mungkin pilihannya bisa ditambah teks:

Buat:
1 (sangat jelek)
2 (jelek)
3 (normal)
4 (baik)
5 (sangat baik)

**Comment by alsasian** [comment]
ini doable

**Comment by alsasian** [comment]
Fixed in https://github.com/jendela/jendela/pull/94
