### ISSUE TITLE
PENTING: field biaya di tulis ulasan

### ISSUE THREAD

**Issue by yoelsumitro** [jendela/jendela#91]
Field biaya di tulis ulasan harusnya bukan dropdown menu tapi free text field

**Comment by alsasian** [comment]
fieldnya bukan dropdown menu el, tapi field dengan tipe number. Somehow muncul arrow up and down. Menurut gw ga kritikal karena user masih bisa input biaya.

Kalo free text, gw khawatir mesti ngevalidasi input n ngubah struktur dbnya...

**Comment by yoelsumitro** [comment]
ah i see. soalnya abis ngisi rating gw liat dropdown icon yg sama. Jadi langsung mikirnya itu dropdown menu. Kalau gitu yang rating bisa diganti ga sa? at least beneran jadi kaya dropdown menu. jadi bedain sama yg biaya ini/

**Comment by alsasian** [comment]
ok el, bisa di ganti ko yang rating. i will try to make it a star input.
