### ISSUE TITLE
add syarat dan ketentuan + minta NIK/pasport di tulis ulasan

### ISSUE THREAD

**Issue by yoelsumitro** [jendela/jendela#98]

**Comment by yoelsumitro** [comment]
[Syarat dan Ketentuan.docx](https://github.com/jendela/jendela/files/53108/Syarat.dan.Ketentuan.docx)

**Comment by yoelsumitro** [comment]
![ganti dikit tulis ulasan](https://cloud.githubusercontent.com/assets/16069578/11612702/04a0c6c0-9c05-11e5-8ea8-de73c56249a3.PNG)

layout tambahan pake NIK

**Comment by alsasian** [comment]
Added in https://github.com/jendela/jendela/pull/107

**Comment by yoelsumitro** [comment]
Sa. yang permintaan NIK nama telp and email harus dibuka terus sa. Trus ditambahin disclaimer kaya yang gw tunjukkin di layout diatas.

**Comment by alsasian** [comment]
Fixed in https://github.com/jendela/jendela/pull/111

**Comment by yoelsumitro** [comment]
Ketika checkbox saya ingin menulis nama secara anonim, field yang data personal tetap dibuka. Jadi itu wajib buat semua org sa. Krn kita butuh buat verifikasi.Cuman org bisa milih buat nampilin atau ga.

**Comment by alsasian** [comment]
i see el, i got a bit confused with the previous sentence. I'll modify so it no longer has hide/show behavior

**Comment by alsasian** [comment]
Gw bisa ubah behaviornya el supaya keep open.

Btw, ketika lo bilang nampilin, itu maksudnya di ulasan ya? ada hal yang aneh menurut gw. Kalo lo bilang bisa nampilin ato ngga, kalimat yang diatas (_Data personal dibawah ini tidak akan di..._) ga valid dong? 

Apa perlu kita lengkapin kalimatnya dengan kalimat seperti "_Jika memilih anonim, data di bawah ini..._"

**Comment by yoelsumitro** [comment]
Iya sa bagus idenya. Gitu aja
